name: Java CI/CD with Gradle
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # permissions:
  # contents: read
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for coverage comparison

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setting Permissions
        run: chmod a+x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test

      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport

      - name: Jacoco Coverage Report
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-coverage-badge: true
          generate-branches-badge: true
          generate-coverage-endpoint: true
          generate-branches-endpoint: true
          coverage-label: coverage
          branches-label: branches
          fail-if-coverage-less-than: 0  # Don't fail based on absolute threshold
          fail-if-branches-less-than: 0  # Don't fail based on absolute threshold
          fail-if-coverage-decrease: true  # Fail if coverage decreases from previous run
          fail-if-branches-decrease: true  # Fail if branch coverage decreases from previous run
          jacoco-badge-file: .github/badges/jacoco.svg
          branches-badge-file: .github/badges/branches.svg
          coverage-endpoint-file: .github/badges/jacoco.json
          branches-endpoint-file: .github/badges/branches.json

      - name: Log Coverage Percentage
        run: |
          echo "Line Coverage: ${{ steps.jacoco.outputs.coverage }}"
          echo "Branch Coverage: ${{ steps.jacoco.outputs.branches }}"

  build_and_publish_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}