name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Download previous coverage artifact (if it exists)
      - name: Download previous coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: previousCoverage
          path: .
          if-no-files-found: 'ignore'

      # Read the previous branch coverage value from file, or default to 0 if not present.
      - name: Set previous coverage env variable
        id: set_prev_cov
        run: |
          if [ -f "coverage.txt" ]; then
            prev=$(cat coverage.txt)
            echo "Previous branch coverage: $prev"
          else
            echo "No previous coverage found. Defaulting to 0."
            prev=0
          fi
          echo "PREV_COV=$prev" >> $GITHUB_ENV
          echo "::set-output name=prev_cov::$prev"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setting Permissions
        run: chmod a+x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test

      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport

      # Run jacoco badge generator. Its "fail-if-branches-less-than" input is set to the previous branch coverage.
      - name: Jacoco
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          fail-if-branches-less-than: ${{ env.PREV_COV }}

      # Save the current branch coverage output into a file for the next run.
      - name: Save current branch coverage
        run: |
          echo "${{ steps.jacoco.outputs.branchCoverage }}" > coverage.txt

      # Upload the current coverage file as an artifact to be available in the next run.
      - name: Upload current coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: previousCoverage
          path: coverage.txt

  build_and_publish_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
